services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_API_URL=http://user_service:3000
    depends_on:
      - user_service
      - avatar_service

  user_service:
    container_name: user_service
    build: ./user_service
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=${DB_PATH}
    volumes:
      - ./user_service:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - avatar_service

  avatar_service:
    container_name: avatar_service
    build: ./avatar_service
    ports:
      - "3001:3001"
    volumes:
      - ./avatar_service:/app
      - /app/node_modules
    command: npm start